schema = 3

[mod]
  [mod."github.com/av-elier/go-decimal-to-rational"]
    version = "v0.0.0-20191127152832-89e6aad02ecf"
    hash = "sha256-134e6CsH7ukNl3ew3CW/8+DvBtsiaIXn5YlP1+fWUpQ="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/djherbis/times"]
    version = "v1.5.0"
    hash = "sha256-3i0MAv5bCzAJ3zriOcOHv+rcZwHTm3CFcb64KF8edPc="
  [mod."github.com/dsoprea/go-exif/v3"]
    version = "v3.0.0-20210625224831-a6301f85c82b"
    hash = "sha256-LhB2EGg5tJpKB5afsQiwqPLCKbkBaFtnnmCpdDwlehY="
  [mod."github.com/dsoprea/go-iptc"]
    version = "v0.0.0-20200610044640-bc9ca208b413"
    hash = "sha256-4Kgsxl2iXvUPLItfTO04wx0ABg84bPJG2+VhTkxjpqQ="
  [mod."github.com/dsoprea/go-jpeg-image-structure/v2"]
    version = "v2.0.0-20210512043942-b434301c6836"
    hash = "sha256-mpepPOX0B0873VC8H+IZ93O/dsSOmeHZ1k47Tf5E9kk="
  [mod."github.com/dsoprea/go-logging"]
    version = "v0.0.0-20200710184922-b02d349568dd"
    hash = "sha256-qc4Nzj7uHl5VRc5Q+iXVCjOmfDQl5wIoiuJKque5jCY="
  [mod."github.com/dsoprea/go-photoshop-info-format"]
    version = "v0.0.0-20200610045659-121dd752914d"
    hash = "sha256-IEtAX9Gd1VVNdtYoUcGBS07GyVpksSx3cQKFEgDOIGA="
  [mod."github.com/dsoprea/go-utility/v2"]
    version = "v2.0.0-20200717064901-2fccff4aa15e"
    hash = "sha256-fFgy5LuP6chSY+4K0GbqIGAiZdQ9PwKJdGhHxmpSvg4="
  [mod."github.com/go-errors/errors"]
    version = "v1.4.2"
    hash = "sha256-TkRLJlgaVlNxRD9c0ky+CN99tKL4Gx9W06H5a273gPM="
  [mod."github.com/go-xmlfmt/xmlfmt"]
    version = "v0.0.0-20191208150333-d5b6f63a941b"
    hash = "sha256-ahh/mWwt4kWtdDE55n96nX1BQl73/5yUnqN07BimAr4="
  [mod."github.com/golang/geo"]
    version = "v0.0.0-20210211234256-740aa86cb551"
    hash = "sha256-CYJ6iVacxRptp7NNrJxgt1lCaKTi89rIi6qMR1lR+So="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.0"
    hash = "sha256-ogTuLrV40FwS4ueo4hh6hi1wPywOI+LyIqfNjsibwNY="
  [mod."github.com/kr/pretty"]
    version = "v0.1.0"
    hash = "sha256-Fx+TaNrxW0VfzonT2jnd5MU09RRz7GJZkqAtJR6/pKI="
  [mod."github.com/maxatome/go-testdeep"]
    version = "v1.11.0"
    hash = "sha256-1ZN00eeXAEsvSksScSHryS73+sONXyjw2eTsfW+M1k4="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/spf13/cobra"]
    version = "v1.5.0"
    hash = "sha256-rcyHWrxshA5DVpxrSba5X4NjppqOGrJ64QkUKKnfW2E="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.0"
    hash = "sha256-LDxBAebK+A06y4vbH7cd1sVBOameIY81Xm8/9OPZh7o="
  [mod."github.com/tkrajina/gpxgo"]
    version = "v1.2.1"
    hash = "sha256-VTmlmh8om0OknMxY7+kzuc9X+zufBiCuKpDHXlab0/8="
  [mod."github.com/zsefvlol/timezonemapper"]
    version = "v1.0.0"
    hash = "sha256-ipz1r+bhqqwLXD7n50dgqvm28Mw5SONWBYHsPzr0HMg="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220802222814-0bcc04d9c69b"
    hash = "sha256-/cX5OEAvYf6ohCgq8Ly7xQ1yiAS2q9cAQWherN3t9v0="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20180628173108-788fd7840127"
    hash = "sha256-KsRJNTprd1UijnJusbHwQGM7Bdm45Jt/QL+cIUGNa2w="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
